name: Ballerina GraphQL Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'implementations/ballerina/**'

jobs:
  compatibility:
    uses: ./.github/workflows/test-subgraph.yaml
    with:
      # should match folder name
      library: "ballerina"

  pr-info:
    uses: ./.github/workflows/save-pr-info.yaml
    with:
      pr_number: ${{ github.event.number }}
